name : monitor cargador Iberdrola
on:
  schedule :
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutar monitor
        run: echo "Monitor iniciado"
        
